### ISSUE TITLE
lennormalize.py: wrong example command

### ISSUE THREAD

**Issue by thedam** [VUmcCGP/wisexome#1]
Hey,
In the READM.md you have a command:
`python lennormalize.py convert/samplename.hits captureregions.bed leno/samplename.hits`
that doesn't work.
You should change it to make people aware how to run your program. This works:
`python lennormalize.py convert captureregions.bed leno`

Cheers
Damian Loska

**Comment by tiagobrc** [comment]
Thank you Damian, 

I almost got crazy! Your example worked!

**Comment by thedam** [comment]
Still I didn't test the further steps, I'll do it later :)
